config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('jat.urls')),
    path('admin/', admin.site.urls),
]

jat/urls.py
from django.urls import path

from jat import views

app_name = 'jat'

urlpatterns = [
    path('', views.RepositoryListView.as_view(), name='repository_list'),    #jat:repository_list
    path('repository/<int:pk>/', views.RepositoryDetailView.as_view(), name='repository_detail'),    #jat:repository_detail
    path('repository/<int:repository_pk>/introduction/<int:pk>/', views.IntroductionDetailView.as_view(), name='introduction_detail'),    #jat:introduction_detail
    path('repository/add/', views.RepositoryCreateView.as_view(), name='repository_add'),    #jat:repository_add
    path('repository/<int:pk>/modify/', views.RepositoryUpdateView.as_view(), name='repository_modify'),    #jat:repository_modify
    path('repository/<int:pk>/delete/', views.RepositoryDeleteView.as_view(), name='repository_delete'),    #jat:repository_delete
    path('repository/<int:repository_pk>/introduction/add/', views.add_introduction, name='introduction_add'),
    # path('repository/<int:repository_pk>/introduction/add/', views.IntroductionCreateView.as_view(), name='introduction_add'),
    path('repository/<int:repository_pk>/introduction/<int:pk>/modify/', views.IntroductionUpdateView.as_view(), name='introduction_modify'),
    path('repository/<int:repository_pk>/introduction/<int:pk>/delete/', views.IntroductionDeleteView.as_view(), name='introduction_delete'),
    path('repository/<int:repository_pk>/introduction/<int:introduction_pk>/comment/add/', views.CommentCreateView.as_view(), name='comment_add'),
    path('repository/<int:repository_pk>/introduction/<int:introduction_pk>/comment/<int:pk>/modify/', views.CommentUpdateView.as_view(), name='comment_modify'),
    path('repository/<int:repository_pk>/introduction/<int:introduction_pk>/comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

jat/models.py
from django.db import models


class Repository(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=200)
    deadline = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # repo1.introduction_set
    class Meta:
        verbose_name_plural = 'Repositories'
        ordering = ['deadline']

    def __str__(self):
        return self.name


class Introduction(models.Model):
    repository = models.ForeignKey(Repository, on_delete=models.CASCADE)  # intro1.repository
    version = models.IntegerField(default=1)
    contents = models.TextField()
    access = models.IntegerField(default=1)  # 0: private, 1: public

    # intro1.comment_set
    class Meta:
        ordering = ['-version']

    def __str__(self):
        return f'{self.version} {self.contents}'


class Comment(models.Model):
    introduction = models.ForeignKey(Introduction, on_delete=models.CASCADE)  # comm1.introduction
    comment = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.comment

jat/forms.py
from django import forms

from jat.models import Introduction


class IntroductionForm(forms.ModelForm):
    class Meta:
        model = Introduction
        fields = ['repository', 'version', 'contents', 'access']  # '__all__'

jat/views.py
from django.db.models import Max
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from jat.forms import IntroductionForm
from jat.models import Repository, Introduction, Comment


class RepositoryListView(generic.ListView):
    model = Repository


class RepositoryDetailView(generic.DetailView):
    model = Repository


class RepositoryCreateView(generic.CreateView):
    model = Repository
    fields = ['name', 'description', 'deadline']  # '__all__'
    template_name_suffix = '_create'
    success_url = reverse_lazy('jat:repository_list')


class RepositoryUpdateView(generic.UpdateView):
    model = Repository
    fields = ['name', 'description', 'deadline']  # '__all__'
    template_name_suffix = '_update'
    success_url = reverse_lazy('jat:repository_list')


class RepositoryDeleteView(generic.DeleteView):
    model = Repository
    success_url = reverse_lazy('jat:repository_list')


class IntroductionDetailView(generic.DetailView):
    model = Introduction


class IntroductionCreateView(generic.CreateView):
    model = Introduction
    fields = ['repository', 'version', 'contents', 'access']  # '__all__'
    template_name_suffix = '_create'

    # success_url = reverse_lazy('jat:repository_detail') #repository_detail은 pk가 필요함(ImproperlyConfigured at /repository/3/introduction/add/)
    def get_initial(self):
        repository = get_object_or_404(Repository, pk=self.kwargs['repository_pk'])
        introduction = repository.introduction_set.aggregate(
            Max('version'))  # 해당 repository의 introduction 중 version 최대값 구하자
        version = introduction['version__max']
        if version == None:  # introduction이 아예 없으면 version 기본값: 1
            version = 1
        else:  # introduction이 있으면 version 최대값에서 +1
            version += 1
        return {'repository': repository, 'version': version}

    def get_success_url(self):
        return reverse_lazy('jat:repository_detail', kwargs={'pk': self.kwargs['repository_pk']})


def add_introduction(request, repository_pk):  # return render(request, '템플릿 이름', 그템플릿에 넘겨주는 context)
    if request.method == 'POST':    #POST라면
        form = IntroductionForm(request.POST)   #  introduction 만드는 form에서 입력한 정보 가져오자
        if form.is_valid(): #  그 정보가 확인되면
            form.save()     #    DB에 저장
            return redirect('jat:repository_detail', pk=repository_pk)   #    repository_detail로 redirect
    else:   #POST가 아니면(요청한 것: introduction 만들기위한 form 보여주기)
        repository = get_object_or_404(Repository, pk=repository_pk)    #  repository를 DB에서 꺼내자
        introduction = repository.introduction_set.order_by('-version').first()
        #  version을 구하자
        #  contents(introduction 내용) 가져오자
        if introduction == None:
            version = 1     #    introduction이 없으면 version = 1
            contents = ''   #    introduction이 없으면 ''
            access = 1
        else:
            version = introduction.version + 1  #    repository에 있는 introduction 중 가장 큰 버전 + 1
            contents = introduction.contents    #    introduction 중 가장 큰 버전의 contents를 가져오자
            access = introduction.access
        initial = {'repository': repository, 'version': version, 'contents': contents, 'access': access}
        form = IntroductionForm(initial=initial)   #  form 가져오자
        context = {'form': form, 'repository': repository}    #  context = form, repository

    return render(request, 'jat/introduction_create.html', context)



class IntroductionUpdateView(generic.UpdateView):
    model = Introduction
    fields = ['repository', 'version', 'contents', 'access']  # '__all__'
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse_lazy('jat:repository_detail', kwargs={'pk': self.kwargs['repository_pk']})


class IntroductionDeleteView(generic.DeleteView):
    model = Introduction

    def get_success_url(self):
        return reverse_lazy('jat:repository_detail', kwargs={'pk': self.kwargs['repository_pk']})


class CommentCreateView(generic.CreateView):  # repository/<int:repository_pk>/introduction/<int:introduction_pk>/comment/add/
    model = Comment
    fields = '__all__'  # ['introduction', 'comment']
    template_name_suffix = '_create'  # comment_create.html

    def get_initial(self):
        introduction = get_object_or_404(Introduction, pk=self.kwargs['introduction_pk'])
        return {'introduction': introduction}

    def get_success_url(self):  # jat:introduction_detail repository_pk pk
        kwargs = {
            'repository_pk': self.kwargs['repository_pk'],
            'pk': self.kwargs['introduction_pk'],
        }
        return reverse_lazy('jat:introduction_detail', kwargs=kwargs)   #repository/<int:repository_pk>/introduction/<int:pk>/


class CommentUpdateView(generic.UpdateView):
    model = Comment
    fields = '__all__'  # ['introduction', 'comment']
    template_name_suffix = '_update'  # comment_update.html

    def get_success_url(self):  # jat:introduction_detail repository_pk pk
        kwargs = {
            'repository_pk': self.kwargs['repository_pk'],
            'pk': self.kwargs['introduction_pk'],
        }
        return reverse_lazy('jat:introduction_detail', kwargs=kwargs)  # repository/<int:repository_pk>/introduction/<int:pk>/


class CommentDeleteView(generic.DeleteView):
    model = Comment

    def get_success_url(self):  # jat:introduction_detail repository_pk pk
        kwargs = {
            'repository_pk': self.kwargs['repository_pk'],
            'pk': self.kwargs['introduction_pk'],
        }
        return reverse_lazy('jat:introduction_detail', kwargs=kwargs)  # repository/<int:repository_pk>/introduction/<int:pk>/

jat/templates/jat/comment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Comment{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Do you want to delete Comment "{{ comment }}"?
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back();">Cancel</button>
    </form>
{% endblock %}

jat/templates/jat/comment_create.html
{% extends 'base.html' %}

{% block title %}Add Comment{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

jat/templates/jat/comment_update.html
{% extends 'base.html' %}

{% block title %}Update Comment{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

jat/templates/jat/introduction_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Introduction{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Do you want to delete Introduction "{{ introduction }}"?
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back();">Cancel</button>
    </form>
{% endblock %}

jat/templates/jat/introduction_create.html
{% extends 'base.html' %}

{% block title %}Add Introduction{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
    <ul>
        {% for introduction in repository.introduction_set.all %}
            <li>version {{ introduction.version }}</li>
        {% endfor %}
    </ul>
{% endblock %}

jat/templates/jat/introduction_detail.html
{% extends 'base.html' %}

{% block title %}Detail Introduction{% endblock %}

{% block content %}
    {{ introduction.contents }}
    <a href="{% url 'jat:comment_add' repository_pk=introduction.repository_id introduction_pk=introduction.pk %}">Add Comment</a>
    <table class="table">
        <tbody>
        {% for comment in introduction.comment_set.all %}
            <tr>
                <td>{{ comment.comment }}</td>
                <td><a href="{% url 'jat:comment_modify' repository_pk=introduction.repository_id introduction_pk=introduction.pk pk=comment.pk %}" class="btn btn-success">수정</a></td>
                <td><a href="{% url 'jat:comment_delete' repository_pk=introduction.repository_id introduction_pk=introduction.pk pk=comment.pk %}" class="btn btn-danger">삭제</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

jat/templates/jat/introduction_update.html
{% extends 'base.html' %}

{% block title %}Update Introduction{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

jat/templates/jat/repository_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete Repository{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        Do you want to delete Repository "{{ repository }}"?
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back();">Cancel</button>
    </form>
{% endblock %}

jat/templates/jat/repository_create.html
{% extends 'base.html' %}

{% block title %}Add Repository{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

jat/templates/jat/repository_detail.html
{% extends 'base.html' %}

{% block title %}Detail Repository{% endblock %}

{% block content %}
    {{ repository.name }}
    <a href="{% url 'jat:introduction_add' repository_pk=repository.pk %}"><i class="bi bi-plus-circle-fill"></i></a>
    <table class="table">
        <tbody>
        {% for introduction in repository.introduction_set.all %}
            <tr>
                <td>Version: <a href="{% url 'jat:introduction_detail' repository_pk=repository.pk pk=introduction.pk %}">{{ introduction.version }}</a></td>
                <td><a href="{% url 'jat:introduction_delete' repository_pk=repository.pk pk=introduction.pk %}"><i class="bi bi-trash"></i></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

jat/templates/jat/repository_list.html
{% extends 'base.html' %}

{% block title %}List Repository{% endblock %}

{% block content %}
    {{ repository_list.count }} Repository
    <a href="{% url 'jat:repository_add' %}"><i class="bi bi-plus-lg"></i></a>
    <table class="table w-50">
        <tbody>
        {% for repository in repository_list %}
            <tr>
                <td class="align-middle"><a href="{% url 'jat:repository_modify' pk=repository.pk %}"><i class="bi bi-pencil-fill"></i></a></td>
                <td>
                    <a href="{% url 'jat:repository_detail' pk=repository.pk %}">{{ repository.name }}<br>
                    Date: {{ repository.deadline|date:'Y/m/d h:i' }}</a>
                </td>
                <td class="align-middle"><a href="{% url 'jat:repository_delete' pk=repository.pk %}"><i class="bi bi-trash"></i></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

jat/templates/jat/repository_update.html
{% extends 'base.html' %}

{% block title %}Update Repository{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <button type="submit">Update</button>
    </form>
{% endblock %}